resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: development

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    buildDockerArtifact: false
    mavenGoals: deploy
    jiraVersionPrefix: Common
    deployOssrh: true

trigger:
  batch: true
  branches:
    include:
      - '*'

pr: none
