//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.difi.meldingsutveksling.domain.sbdh;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import no.difi.meldingsutveksling.validation.SenderValue;
import no.difi.meldingsutveksling.validation.group.ValidationGroups;

import jakarta.validation.constraints.NotNull;
import jakarta.xml.bind.annotation.*;
import java.io.Serializable;

/**
 * Java class for PartnerIdentification complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="PartnerIdentification">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *       <attribute name="Authority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerIdentification", propOrder = {
        "value"
})
@Data
@RequiredArgsConstructor
public class PartnerIdentification implements Serializable {

    @XmlValue
    @SenderValue(groups = ValidationGroups.Partner.Sender.class)
    @NotNull
    protected String value;

    @XmlAttribute(name = "Authority")
    @NotNull
    protected String authority;
}
