//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.11.25 at 12:23:12 PM CET
//


package no.difi.meldingsutveksling.domain.sbdh;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import no.difi.meldingsutveksling.validation.OneOf;
import no.difi.meldingsutveksling.validation.SbdScopeConditionalInstanceIdentifierUuid;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.HashSet;
import java.util.Set;


/**
 * Java class for Scope complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="Scope">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <group ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}ScopeAttributes"/>
 *         <element ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}ScopeInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Scope", propOrder = {
        "type",
        "instanceIdentifier",
        "identifier",
        "scopeInformation"
})
@Getter
@Setter
@ToString
@SbdScopeConditionalInstanceIdentifierUuid
public class Scope {

    @XmlElement(name = "Type", required = true)
    @NotNull
    @OneOf({"JournalpostId", "ConversationId", "SenderRef", "ReceiverRef", "MessageChannel","SenderHerId1","SenderHerId2","ReceiverHerId1","ReceiverHerId2"})
    protected String type;

    @XmlElement(name = "InstanceIdentifier", required = true)
    protected String instanceIdentifier;

    @XmlElement(name = "Identifier")
    protected String identifier;

    @XmlElement(name = "ScopeInformation")
    @Valid
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    protected Set<@Valid CorrelationInformation> scopeInformation;

    /**
     * Gets the value of the scopeInformation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scopeInformation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScopeInformation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BusinessService }{@code >}
     * {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     * @return scope information
     */
    public Set<CorrelationInformation> getScopeInformation() {
        if (scopeInformation == null) {
            scopeInformation = new HashSet<>();
        }
        return this.scopeInformation;
    }

    public Scope addScopeInformation(CorrelationInformation correlationInformation) {
        getScopeInformation().add(correlationInformation);
        return this;
    }
}
