//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.difi.meldingsutveksling.domain.sbdh;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import no.difi.meldingsutveksling.domain.PartnerIdentifier;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.*;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.Optional;
import java.util.Set;


/**
 * Java class for StandardBusinessDocument complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="StandardBusinessDocument">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}StandardBusinessDocumentHeader" minOccurs="0"/>
 *         <any processContents='lax' namespace='##other'/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardBusinessDocument", propOrder = {
        "standardBusinessDocumentHeader",
        "any"
})
@Data
public class StandardBusinessDocument {

    @XmlElement(name = "StandardBusinessDocumentHeader")
    @NotNull
    @Valid
    private StandardBusinessDocumentHeader standardBusinessDocumentHeader;

    @XmlAnyElement(lax = true)
    @NotNull
    private Object any;

    @JsonIgnore
    public <T> Optional<T> getBusinessMessage(Class<T> clazz) {
        return clazz.isInstance(any) ? Optional.of(clazz.cast(any)) : Optional.empty();
    }

    @JsonIgnore
    public Optional<String> getMessageId() {
        return Optional.ofNullable(standardBusinessDocumentHeader.getDocumentIdentification())
                .flatMap(p -> Optional.ofNullable(p.getInstanceIdentifier()));
    }

    @JsonIgnore
    public Optional<String> getDocumentType() {
        return Optional.ofNullable(standardBusinessDocumentHeader.getDocumentIdentification())
                .flatMap(p -> Optional.ofNullable(p.getStandard()));
    }

    @JsonIgnore
    public Set<Scope> getScopes() {
        return Optional.ofNullable(standardBusinessDocumentHeader.getBusinessScope())
                .flatMap(p -> Optional.ofNullable(p.getScope()))
                .orElseGet(Collections::emptySet);
    }

    @JsonIgnore
    public Optional<Scope> getScope(ScopeType scopeType) {
        return standardBusinessDocumentHeader.getScopes()
                .stream()
                .filter(scope -> scopeType.toString().equals(scope.getType()) || scopeType.name().equals(scope.getType()))
                .findAny();
    }

    @JsonIgnore
    public void addScope(Scope scope) {
        Optional.ofNullable(standardBusinessDocumentHeader.getBusinessScope()).ifPresent(p -> p.addScopes(scope));
    }

    @JsonIgnore
    public Optional<String> getConversationId() {
        return standardBusinessDocumentHeader.getConversationId();
    }

    @JsonIgnore
    public Optional<String> getType() {
        return Optional.ofNullable(standardBusinessDocumentHeader.getDocumentIdentification())
                .flatMap(p -> Optional.ofNullable(p.getType()));
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getExpectedResponseDateTime() {
        return standardBusinessDocumentHeader.getExpectedResponseDateTime();
    }

    @JsonIgnore
    public PartnerIdentifier getSenderIdentifier() {
        return standardBusinessDocumentHeader.getSenderIdentifier();
    }

    @JsonIgnore
    public StandardBusinessDocumentHeader setSenderIdentifier(PartnerIdentifier identifier) {
        return standardBusinessDocumentHeader.setSenderIdentifier(identifier);
    }

    @JsonIgnore
    public PartnerIdentifier getReceiverIdentifier() {
        return standardBusinessDocumentHeader.getReceiverIdentifier();
    }

    @JsonIgnore
    public StandardBusinessDocumentHeader setReceiverdentifier(PartnerIdentifier identifier) {
        return standardBusinessDocumentHeader.setReceiverIdentifier(identifier);
    }
}
