name: CI Workflow

on:
  push:
    branches: [ main ]

jobs:

  build-install-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      java-version: 21
      sbom-path: .
    secrets: inherit
