name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      profile:
        description: 'Build profile'
        required: true
        default: 'new-platform'
  push:
    branches:
      - '*'
  pull_request:
    types: [ ]  # Empty list ensures PRs are not triggered. Trigger nytt bygg.

jobs:

  build-install-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      java-version: 21
      sbom-path: .
      profile: new-platform
    secrets: inherit