name: Maven build

on:
  push:
    branches: [main]

  workflow_call:

  repository_dispatch:
    types: [build-publish-image]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build-lib.yml@main
    with:
      java-version: 21
      sbom-path: ./
    secrets: inherit